// Chinesisch festigen – Zeichen-Bausteine (App-Ebene, getrennt vom Buch)
// Zweck: Schreibtraining zeichenbasiert mit Dedup. Jedes Zeichen kommt nur EINMAL
// über alle Wörter vor. Pinyin steht hier silbenweise pro Zeichen (topics.js hat
// nur das Wort-Pinyin), damit Mehrzeichenwörter nicht mismatchen.
//
// Jedes Zeichen hat eine eigene Übersetzung (de). word/wordPy/wordDe = das Wort,
// in dem das Zeichen im Kapitel vorkommt (für „ganzes Wort über dem Zeichen",
// aktuelles Zeichen farbig, und für den Hinweis „Teil von …").
// review:true = Bedeutung von der/dem Beijing-Kontakt prüfen lassen
//   (v. a. gebundene/grammatische Silben, deren Einzelbedeutung wackelig ist).

window.CF_BAUSTEINE = {
  "01": {
    order: ["我","你","是","不","也","从","吗","呢","叫","看","来","好","手","机","人","名","字","什","么","哪","国","德","北","京","上","海","对","起","没","关","系","谢","再","见"],
    chars: {
      "我": { py:"wǒ",   de:"ich",                    word:"我",     wordPy:"wǒ",         wordDe:"ich" },
      "你": { py:"nǐ",   de:"du",                     word:"你",     wordPy:"nǐ",         wordDe:"du" },
      "是": { py:"shì",  de:"sein (ist)",             word:"是",     wordPy:"shì",        wordDe:"sein" },
      "不": { py:"bù",   de:"nicht",                  word:"不",     wordPy:"bù",         wordDe:"nicht" },
      "也": { py:"yě",   de:"auch",                   word:"也",     wordPy:"yě",         wordDe:"auch" },
      "从": { py:"cóng", de:"von, aus",               word:"从",     wordPy:"cóng",       wordDe:"von, aus" },
      "吗": { py:"ma",   de:"Fragepartikel (Ja/Nein-Frage)", word:"吗", wordPy:"ma",     wordDe:"Fragepartikel" },
      "呢": { py:"ne",   de:"Fragepartikel („und …?“)",      word:"你呢", wordPy:"nǐ ne", wordDe:"Und du?" },
      "叫": { py:"jiào", de:"heißen, rufen",          word:"叫",     wordPy:"jiào",       wordDe:"heißen" },
      "看": { py:"kàn",  de:"schauen, sehen",         word:"看",     wordPy:"kàn",        wordDe:"schauen" },
      "来": { py:"lái",  de:"kommen",                 word:"来",     wordPy:"lái",        wordDe:"kommen" },
      "好": { py:"hǎo",  de:"gut",                    word:"好",     wordPy:"hǎo",        wordDe:"gut" },
      "手": { py:"shǒu", de:"Hand",                   word:"手机",   wordPy:"shǒujī",     wordDe:"Handy" },
      "机": { py:"jī",   de:"Maschine, Gerät",        word:"手机",   wordPy:"shǒujī",     wordDe:"Handy" },
      "人": { py:"rén",  de:"Mensch, Person",         word:"人",     wordPy:"rén",        wordDe:"Mensch" },
      "名": { py:"míng", de:"Name",                   word:"名字",   wordPy:"míngzi",     wordDe:"Name" },
      "字": { py:"zì",   de:"(Schrift-)Zeichen, Wort",word:"名字",   wordPy:"míngzi",     wordDe:"Name" },
      "什": { py:"shén", de:"Frage-Silbe",            word:"什么",   wordPy:"shénme",     wordDe:"was", review:true },
      "么": { py:"me",   de:"Frage-/Suffixsilbe",     word:"什么",   wordPy:"shénme",     wordDe:"was", review:true },
      "哪": { py:"nǎ",   de:"welche/r/s (Frage)",     word:"哪",     wordPy:"nǎ",         wordDe:"welche/r/s" },
      "国": { py:"guó",  de:"Land",                   word:"国",     wordPy:"guó",        wordDe:"Land" },
      "德": { py:"dé",   de:"Tugend",                 word:"德国",   wordPy:"Déguó",      wordDe:"Deutschland", review:true },
      "北": { py:"běi",  de:"Norden",                 word:"北京",   wordPy:"Běijīng",    wordDe:"Beijing" },
      "京": { py:"jīng", de:"Hauptstadt",             word:"北京",   wordPy:"Běijīng",    wordDe:"Beijing" },
      "上": { py:"shàng",de:"oben, auf",              word:"上海",   wordPy:"Shànghǎi",   wordDe:"Shanghai" },
      "海": { py:"hǎi",  de:"Meer",                   word:"上海",   wordPy:"Shànghǎi",   wordDe:"Shanghai" },
      "对": { py:"duì",  de:"richtig",                word:"对不起", wordPy:"duìbuqǐ",    wordDe:"Entschuldigung" },
      "起": { py:"qǐ",   de:"(sich) erheben, aufstehen", word:"对不起", wordPy:"duìbuqǐ", wordDe:"Entschuldigung", review:true },
      "没": { py:"méi",  de:"nicht (haben)",          word:"没关系", wordPy:"méi guānxi", wordDe:"macht nichts" },
      "关": { py:"guān", de:"schließen; betreffen",   word:"没关系", wordPy:"méi guānxi", wordDe:"macht nichts", review:true },
      "系": { py:"xì",   de:"verbinden; Bezug",       word:"没关系", wordPy:"méi guānxi", wordDe:"macht nichts", review:true },
      "谢": { py:"xiè",  de:"danken",                 word:"谢谢",   wordPy:"xièxie",     wordDe:"danke" },
      "再": { py:"zài",  de:"wieder, noch einmal",    word:"再见",   wordPy:"zàijiàn",    wordDe:"Auf Wiedersehen" },
      "见": { py:"jiàn", de:"sehen, treffen",         word:"再见",   wordPy:"zàijiàn",    wordDe:"Auf Wiedersehen" }
    }
  },
  "02": {
    order: ["请","问","地","铁","在","哪","里","那","这","出","口","个","去","换","车","对","不","客","气"],
    chars: {
      "请": { py:"qǐng", de:"bitten; höflich (bitte)", word:"请问", wordPy:"qǐngwèn", wordDe:"Entschuldigung (vor einer Frage)" },
      "问": { py:"wèn", de:"fragen", word:"请问", wordPy:"qǐngwèn", wordDe:"Entschuldigung (vor einer Frage)" },
      "地": { py:"dì", de:"Erde, Boden", word:"地铁", wordPy:"dìtiě", wordDe:"U-Bahn" },
      "铁": { py:"tiě", de:"Eisen", word:"地铁", wordPy:"dìtiě", wordDe:"U-Bahn" },
      "在": { py:"zài", de:"sich befinden in/an/bei", word:"在", wordPy:"zài", wordDe:"sich befinden in/an/bei" },
      "哪": { py:"nǎ", de:"welche/r/s (Frage) (aus Kapitel 01)", word:"哪里", wordPy:"nǎlǐ", wordDe:"wo", review:true },
      "里": { py:"lǐ", de:"drin, innen; Ortssilbe", word:"哪里", wordPy:"nǎlǐ", wordDe:"wo" },
      "那": { py:"nà", de:"jene/r/s, dort", word:"那里", wordPy:"nàlǐ", wordDe:"dort" },
      "这": { py:"zhè", de:"diese/r/s, hier", word:"这里", wordPy:"zhèlǐ", wordDe:"hier" },
      "出": { py:"chū", de:"hinaus, heraus", word:"出口", wordPy:"chūkǒu", wordDe:"Ausgang" },
      "口": { py:"kǒu", de:"Mund, Öffnung", word:"出口", wordPy:"chūkǒu", wordDe:"Ausgang" },
      "个": { py:"ge", de:"Stück (Standard-Zählwort)", word:"哪个", wordPy:"nǎge", wordDe:"welche/r/s (vor Substantiv)" },
      "去": { py:"qù", de:"gehen, fahren (zu/nach)", word:"去", wordPy:"qù", wordDe:"gehen, fahren (zu/nach)" },
      "换": { py:"huàn", de:"wechseln, tauschen", word:"换车", wordPy:"huàn chē", wordDe:"umsteigen" },
      "车": { py:"chē", de:"Wagen, Fahrzeug", word:"换车", wordPy:"huàn chē", wordDe:"umsteigen" },
      "对": { py:"duì", de:"richtig, ja (aus 对不起)", word:"对", wordPy:"duì", wordDe:"richtig, ja", review:true },
      "不": { py:"bù", de:"nicht (aus Kapitel 01)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen", review:true },
      "客": { py:"kè", de:"Gast (in 客气: höflich)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen" },
      "气": { py:"qì", de:"Luft, Stimmung (in 客气: höflich)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen" }
    }
  },
  "03": {
    order: ["房","间","预","订","有","身","份","证","护","照","看","卡","密","码","好","像","不","对","试","早","饭","几","点","上","到","一","下"],
    chars: {
      "房": { py:"fáng", de:"Haus, Zimmer", word:"房间", wordPy:"fángjiān", wordDe:"Zimmer" },
      "间": { py:"jiān", de:"Zwischenraum; Zählwort (Räume)", word:"房间", wordPy:"fángjiān", wordDe:"Zimmer" },
      "预": { py:"yù", de:"im Voraus", word:"预订", wordPy:"yùdìng", wordDe:"Reservierung" },
      "订": { py:"dìng", de:"bestellen, festlegen", word:"预订", wordPy:"yùdìng", wordDe:"Reservierung" },
      "有": { py:"yǒu", de:"haben, es gibt", word:"有", wordPy:"yǒu", wordDe:"haben, es gibt" },
      "身": { py:"shēn", de:"Körper", word:"身份证", wordPy:"shēnfènzhèng", wordDe:"Personalausweis" },
      "份": { py:"fèn", de:"Anteil; Zählwort (Dokumente)", word:"身份证", wordPy:"shēnfènzhèng", wordDe:"Personalausweis" },
      "证": { py:"zhèng", de:"Nachweis, Bescheinigung", word:"身份证", wordPy:"shēnfènzhèng", wordDe:"Personalausweis" },
      "护": { py:"hù", de:"schützen", word:"护照", wordPy:"hùzhào", wordDe:"Reisepass" },
      "照": { py:"zhào", de:"leuchten; Foto (in 护照: Pass)", word:"护照", wordPy:"hùzhào", wordDe:"Reisepass" },
      "看": { py:"kàn", de:"schauen, sehen (aus Kapitel 01)", word:"看", wordPy:"kàn", wordDe:"schauen, sehen", review:true },
      "卡": { py:"kǎ", de:"Karte", word:"房卡", wordPy:"fángkǎ", wordDe:"Schlüsselkarte" },
      "密": { py:"mì", de:"geheim, dicht", word:"密码", wordPy:"mìmǎ", wordDe:"Passwort" },
      "码": { py:"mǎ", de:"Code, Zahl (in 密码: Passwort)", word:"密码", wordPy:"mìmǎ", wordDe:"Passwort" },
      "好": { py:"hǎo", de:"gut (aus Kapitel 01)", word:"好像", wordPy:"hǎoxiàng", wordDe:"scheint, wohl", review:true },
      "像": { py:"xiàng", de:"ähneln, scheinen", word:"好像", wordPy:"hǎoxiàng", wordDe:"scheint, wohl" },
      "不": { py:"bù", de:"nicht (aus Kapitel 01)", word:"不对", wordPy:"bù duì", wordDe:"nicht richtig, falsch", review:true },
      "对": { py:"duì", de:"richtig, ja (aus 对不起)", word:"不对", wordPy:"bù duì", wordDe:"nicht richtig, falsch", review:true },
      "试": { py:"shì", de:"probieren, versuchen", word:"试", wordPy:"shì", wordDe:"probieren, versuchen" },
      "早": { py:"zǎo", de:"früh, Morgen", word:"早饭", wordPy:"zǎofàn", wordDe:"Frühstück" },
      "饭": { py:"fàn", de:"Essen, Mahlzeit, Reis", word:"早饭", wordPy:"zǎofàn", wordDe:"Frühstück" },
      "几": { py:"jǐ", de:"wie viele (kleine Zahl)", word:"几点", wordPy:"jǐ diǎn", wordDe:"wie viel Uhr" },
      "点": { py:"diǎn", de:"Punkt; Uhr (Zeitangabe)", word:"几点", wordPy:"jǐ diǎn", wordDe:"wie viel Uhr" },
      "上": { py:"shàng", de:"oben, auf (aus 上海)", word:"早上", wordPy:"zǎoshang", wordDe:"morgens, Morgen", review:true },
      "到": { py:"dào", de:"ankommen; bis", word:"到", wordPy:"dào", wordDe:"bis, ankommen" },
      "一": { py:"yī", de:"eins", word:"一下", wordPy:"yíxià", wordDe:"kurz, mal (mildert das Verb)" },
      "下": { py:"xià", de:"unten; (mal, kurz)", word:"一下", wordPy:"yíxià", wordDe:"kurz, mal (mildert das Verb)" }
    }
  },
  "04": {
    order: ["咖","啡","要","杯","个","吃","喝","面","包","很","还","累","饿","渴","开","心","起","床","上","午","中","下","好","的","不","客","气","厕","所","男","女"],
    chars: {
      "咖": { py:"kā", de:"kā (Lautsilbe, in 咖啡 Kaffee)", word:"咖啡", wordPy:"kāfēi", wordDe:"Kaffee", review:true },
      "啡": { py:"fēi", de:"fēi (Lautsilbe, in 咖啡 Kaffee)", word:"咖啡", wordPy:"kāfēi", wordDe:"Kaffee", review:true },
      "要": { py:"yào", de:"wollen, möchten", word:"要", wordPy:"yào", wordDe:"wollen, möchten" },
      "杯": { py:"bēi", de:"Glas, Tasse (Zählwort)", word:"杯", wordPy:"bēi", wordDe:"Glas, Tasse (Zählwort)" },
      "个": { py:"ge", de:"Stück (Standard-Zählwort) (aus 哪个)", word:"个", wordPy:"ge", wordDe:"Stück (Standard-Zählwort)", review:true },
      "吃": { py:"chī", de:"essen", word:"吃", wordPy:"chī", wordDe:"essen" },
      "喝": { py:"hē", de:"trinken", word:"喝", wordPy:"hē", wordDe:"trinken" },
      "面": { py:"miàn", de:"Gesicht, Seite; Mehl/Nudeln", word:"面包", wordPy:"miànbāo", wordDe:"Brot, Brötchen" },
      "包": { py:"bāo", de:"Tasche; einpacken (in 面包: Brot)", word:"面包", wordPy:"miànbāo", wordDe:"Brot, Brötchen" },
      "很": { py:"hěn", de:"sehr (verbindet Adjektive)", word:"很", wordPy:"hěn", wordDe:"sehr (verbindet Adjektive)" },
      "还": { py:"hái", de:"noch, außerdem", word:"还", wordPy:"hái", wordDe:"noch, außerdem" },
      "累": { py:"lèi", de:"müde", word:"累", wordPy:"lèi", wordDe:"müde" },
      "饿": { py:"è", de:"hungrig", word:"饿", wordPy:"è", wordDe:"hungrig" },
      "渴": { py:"kě", de:"durstig", word:"渴", wordPy:"kě", wordDe:"durstig" },
      "开": { py:"kāi", de:"öffnen; an-/aufmachen", word:"开心", wordPy:"kāixīn", wordDe:"fröhlich, glücklich" },
      "心": { py:"xīn", de:"Herz (in 开心: fröhlich)", word:"开心", wordPy:"kāixīn", wordDe:"fröhlich, glücklich" },
      "起": { py:"qǐ", de:"aufstehen, sich erheben (aus 对不起)", word:"起床", wordPy:"qǐchuáng", wordDe:"aufstehen", review:true },
      "床": { py:"chuáng", de:"Bett (in 起床: aufstehen)", word:"起床", wordPy:"qǐchuáng", wordDe:"aufstehen" },
      "上": { py:"shàng", de:"oben, auf (aus 上海)", word:"上午", wordPy:"shàngwǔ", wordDe:"Vormittag", review:true },
      "午": { py:"wǔ", de:"Mittag", word:"上午", wordPy:"shàngwǔ", wordDe:"Vormittag" },
      "中": { py:"zhōng", de:"Mitte (in 中午: Mittag)", word:"中午", wordPy:"zhōngwǔ", wordDe:"Mittag" },
      "下": { py:"xià", de:"unten; (mal, kurz) (aus 一下)", word:"下午", wordPy:"xiàwǔ", wordDe:"Nachmittag", review:true },
      "好": { py:"hǎo", de:"gut (aus Kapitel 01)", word:"好的", wordPy:"hǎo de", wordDe:"okay, gut", review:true },
      "的": { py:"de", de:"Strukturpartikel (besitzt/bildet Eigenschaft)", word:"好的", wordPy:"hǎo de", wordDe:"okay, gut" },
      "不": { py:"bù", de:"nicht (aus Kapitel 01)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen", review:true },
      "客": { py:"kè", de:"Gast (in 客气: höflich)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen", review:true },
      "气": { py:"qì", de:"Luft, Stimmung (in 客气: höflich)", word:"不客气", wordPy:"bú kèqi", wordDe:"gern geschehen", review:true },
      "厕": { py:"cè", de:"Toilette (in 厕所)", word:"厕所", wordPy:"cèsuǒ", wordDe:"Toilette" },
      "所": { py:"suǒ", de:"Ort (in 厕所: Toilette)", word:"厕所", wordPy:"cèsuǒ", wordDe:"Toilette" },
      "男": { py:"nán", de:"Mann, männlich", word:"男厕所", wordPy:"nán cèsuǒ", wordDe:"Herrentoilette" },
      "女": { py:"nǚ", de:"Frau, weiblich", word:"女厕所", wordPy:"nǚ cèsuǒ", wordDe:"Damentoilette" }
    }
  },
  "05": {
    order: ["买","礼","物","多","少","钱","块","百","条","围","巾","茶","盒","红","色","蓝","绿","的","和","一","共"],
    chars: {
      "买": { py:"mǎi", de:"kaufen", word:"买", wordPy:"mǎi", wordDe:"kaufen" },
      "礼": { py:"lǐ", de:"Geschenk; Höflichkeit", word:"礼物", wordPy:"lǐwù", wordDe:"Geschenk" },
      "物": { py:"wù", de:"Ding, Sache (in 礼物: Geschenk)", word:"礼物", wordPy:"lǐwù", wordDe:"Geschenk" },
      "多": { py:"duō", de:"viel", word:"多少", wordPy:"duōshao", wordDe:"wie viel, wie viele" },
      "少": { py:"shǎo", de:"wenig (in 多少: wie viel)", word:"多少", wordPy:"duōshao", wordDe:"wie viel, wie viele" },
      "钱": { py:"qián", de:"Geld", word:"钱", wordPy:"qián", wordDe:"Geld" },
      "块": { py:"kuài", de:"Stück; Yuan (Geld)", word:"块", wordPy:"kuài", wordDe:"Yuan (umgangssprachlich)" },
      "百": { py:"bǎi", de:"hundert", word:"百", wordPy:"bǎi", wordDe:"hundert" },
      "条": { py:"tiáo", de:"Zählwort (lang/schmal)", word:"条", wordPy:"tiáo", wordDe:"Zählwort (lang/schmal: Schal)" },
      "围": { py:"wéi", de:"umgeben (in 围巾: Schal)", word:"围巾", wordPy:"wéijīn", wordDe:"Schal" },
      "巾": { py:"jīn", de:"Tuch (in 围巾: Schal)", word:"围巾", wordPy:"wéijīn", wordDe:"Schal" },
      "茶": { py:"chá", de:"Tee", word:"茶", wordPy:"chá", wordDe:"Tee" },
      "盒": { py:"hé", de:"Schachtel (Zählwort)", word:"盒", wordPy:"hé", wordDe:"Zählwort (Schachtel)" },
      "红": { py:"hóng", de:"rot", word:"红色", wordPy:"hóngsè", wordDe:"rot" },
      "色": { py:"sè", de:"Farbe", word:"红色", wordPy:"hóngsè", wordDe:"rot" },
      "蓝": { py:"lán", de:"blau", word:"蓝色", wordPy:"lánsè", wordDe:"blau" },
      "绿": { py:"lǜ", de:"grün", word:"绿色", wordPy:"lǜsè", wordDe:"grün" },
      "的": { py:"de", de:"Strukturpartikel (besitzt/bildet Eigenschaft) (aus 好的)", word:"的", wordPy:"de", wordDe:"bildet „die rote“: 红色的", review:true },
      "和": { py:"hé", de:"und (verbindet Nomen)", word:"和", wordPy:"hé", wordDe:"und (verbindet Nomen)" },
      "一": { py:"yī", de:"eins (aus 一下)", word:"一共", wordPy:"yígòng", wordDe:"insgesamt, zusammen", review:true },
      "共": { py:"gòng", de:"gemeinsam, zusammen (in 一共: insgesamt)", word:"一共", wordPy:"yígòng", wordDe:"insgesamt, zusammen" }
    }
  },
  "06": {
    order: ["包","丢","了","能","帮","黑","色","里","面","问","家","饭","馆","喂","真","的","没"],
    chars: {
      "包": { py:"bāo", de:"Tasche; einpacken (in 面包: Brot) (aus 面包)", word:"包", wordPy:"bāo", wordDe:"Tasche, Rucksack", review:true },
      "丢": { py:"diū", de:"verlieren", word:"丢", wordPy:"diū", wordDe:"verlieren" },
      "了": { py:"le", de:"Partikel (Handlung abgeschlossen)", word:"丢了", wordPy:"diū le", wordDe:"verloren, weg" },
      "能": { py:"néng", de:"können", word:"能", wordPy:"néng", wordDe:"können" },
      "帮": { py:"bāng", de:"helfen", word:"帮", wordPy:"bāng", wordDe:"helfen" },
      "黑": { py:"hēi", de:"schwarz", word:"黑色", wordPy:"hēisè", wordDe:"schwarz" },
      "色": { py:"sè", de:"Farbe (aus 红色)", word:"黑色", wordPy:"hēisè", wordDe:"schwarz", review:true },
      "里": { py:"lǐ", de:"drin, innen; Ortssilbe (aus 哪里)", word:"里面", wordPy:"lǐmiàn", wordDe:"drinnen, innen", review:true },
      "面": { py:"miàn", de:"Gesicht, Seite; Mehl/Nudeln (aus 面包)", word:"里面", wordPy:"lǐmiàn", wordDe:"drinnen, innen", review:true },
      "问": { py:"wèn", de:"fragen (aus 请问)", word:"问", wordPy:"wèn", wordDe:"fragen", review:true },
      "家": { py:"jiā", de:"Familie, Zuhause; Zählwort (Läden)", word:"家", wordPy:"jiā", wordDe:"Zählwort (Läden, Lokale)" },
      "饭": { py:"fàn", de:"Essen, Mahlzeit, Reis (aus 早饭)", word:"饭馆", wordPy:"fànguǎn", wordDe:"Restaurant", review:true },
      "馆": { py:"guǎn", de:"Lokal, Halle (in 饭馆: Restaurant)", word:"饭馆", wordPy:"fànguǎn", wordDe:"Restaurant" },
      "喂": { py:"wéi", de:"Hallo (am Telefon)", word:"喂", wordPy:"wéi", wordDe:"Hallo (am Telefon)" },
      "真": { py:"zhēn", de:"wirklich, echt", word:"真的", wordPy:"zhēn de", wordDe:"wirklich" },
      "的": { py:"de", de:"Strukturpartikel (besitzt/bildet Eigenschaft) (aus 好的)", word:"真的", wordPy:"zhēn de", wordDe:"wirklich", review:true },
      "没": { py:"méi", de:"nicht (etwas ist nicht passiert) (aus 没关系)", word:"没找到", wordPy:"méi zhǎodào", wordDe:"nicht gefunden", review:true }
    }
  },
  "07": {
    order: ["饿","菜","单","要","来","碗","盘","米","饭","好","吃","辣","觉","得","干","杯","茶","喜","欢","买","下","次","服","务","员","饼","份","点","推","荐","小","时","候","以","代","酒","我","请","客","够","了","过"],
    chars: {
      "饿": { py:"è", de:"hungrig (aus Kapitel 04)", word:"饿", wordPy:"è", wordDe:"hungrig", review:true },
      "菜": { py:"cài", de:"Gemüse, Gericht, Speise", word:"菜单", wordPy:"càidān", wordDe:"Speisekarte" },
      "单": { py:"dān", de:"Liste, Zettel (in 菜单: Speisekarte)", word:"菜单", wordPy:"càidān", wordDe:"Speisekarte" },
      "要": { py:"yào", de:"wollen, möchten (aus Kapitel 04)", word:"要", wordPy:"yào", wordDe:"wollen, möchten", review:true },
      "来": { py:"lái", de:"kommen; hier: „bringen“ (aus Kapitel 01)", word:"来", wordPy:"lái", wordDe:"hier: „bringen“ (beim Bestellen)", review:true },
      "碗": { py:"wǎn", de:"Schale (Zählwort)", word:"碗", wordPy:"wǎn", wordDe:"Schale (Zählwort)" },
      "盘": { py:"pán", de:"Teller (Zählwort)", word:"盘", wordPy:"pán", wordDe:"Teller (Zählwort)" },
      "米": { py:"mǐ", de:"Reis (roh), Korn", word:"米饭", wordPy:"mǐfàn", wordDe:"Reis" },
      "饭": { py:"fàn", de:"Essen, Mahlzeit, Reis (aus 早饭)", word:"米饭", wordPy:"mǐfàn", wordDe:"Reis", review:true },
      "好": { py:"hǎo", de:"gut (aus Kapitel 01)", word:"好吃", wordPy:"hǎochī", wordDe:"lecker", review:true },
      "吃": { py:"chī", de:"essen (aus Kapitel 04)", word:"好吃", wordPy:"hǎochī", wordDe:"lecker", review:true },
      "辣": { py:"là", de:"scharf", word:"辣", wordPy:"là", wordDe:"scharf" },
      "觉": { py:"jué", de:"fühlen, empfinden", word:"觉得", wordPy:"juéde", wordDe:"finden, meinen" },
      "得": { py:"de", de:"Strukturpartikel (in 觉得: meinen)", word:"觉得", wordPy:"juéde", wordDe:"finden, meinen" },
      "干": { py:"gān", de:"leer, trocken (in 干杯: Prost)", word:"干杯", wordPy:"gānbēi", wordDe:"Prost, anstoßen" },
      "杯": { py:"bēi", de:"Glas, Tasse (Zählwort) (aus Kapitel 04)", word:"干杯", wordPy:"gānbēi", wordDe:"Prost, anstoßen", review:true },
      "茶": { py:"chá", de:"Tee (aus Kapitel 05)", word:"茶", wordPy:"chá", wordDe:"Tee", review:true },
      "喜": { py:"xǐ", de:"mögen, sich freuen", word:"喜欢", wordPy:"xǐhuan", wordDe:"mögen, gern haben" },
      "欢": { py:"huān", de:"froh (in 喜欢: mögen)", word:"喜欢", wordPy:"xǐhuan", wordDe:"mögen, gern haben" },
      "买": { py:"mǎi", de:"kaufen (aus Kapitel 05)", word:"买单", wordPy:"mǎidān", wordDe:"die Rechnung (zahlen)", review:true },
      "下": { py:"xià", de:"unten; (mal, kurz) (aus 一下)", word:"下次", wordPy:"xiàcì", wordDe:"nächstes Mal", review:true },
      "次": { py:"cì", de:"Mal (Zählwort)", word:"下次", wordPy:"xiàcì", wordDe:"nächstes Mal" },
      "服": { py:"fú", de:"dienen (in 服务员: Kellner)", word:"服务员", wordPy:"fúwùyuán", wordDe:"Kellner/in" },
      "务": { py:"wù", de:"Aufgabe, Dienst (in 服务员)", word:"服务员", wordPy:"fúwùyuán", wordDe:"Kellner/in" },
      "员": { py:"yuán", de:"Person, Mitglied (in 服务员)", word:"服务员", wordPy:"fúwùyuán", wordDe:"Kellner/in" },
      "饼": { py:"bǐng", de:"Fladen, dünner Pfannkuchen", word:"饼", wordPy:"bǐng", wordDe:"(dünner) Pfannkuchen, Fladen" },
      "份": { py:"fèn", de:"Anteil; Portion/Zählwort (aus 身份证)", word:"份", wordPy:"fèn", wordDe:"Portion (Zählwort)", review:true },
      "点": { py:"diǎn", de:"Punkt, Uhr; hier: bestellen (aus Kapitel 03)", word:"点", wordPy:"diǎn", wordDe:"bestellen, auswählen", review:true },
      "推": { py:"tuī", de:"schieben; empfehlen", word:"推荐", wordPy:"tuījiàn", wordDe:"empfehlen" },
      "荐": { py:"jiàn", de:"empfehlen (in 推荐)", word:"推荐", wordPy:"tuījiàn", wordDe:"empfehlen" },
      "小": { py:"xiǎo", de:"klein", word:"小时候", wordPy:"xiǎoshíhou", wordDe:"als Kind, in der Kindheit" },
      "时": { py:"shí", de:"Zeit, Stunde", word:"小时候", wordPy:"xiǎoshíhou", wordDe:"als Kind, in der Kindheit" },
      "候": { py:"hòu", de:"Zeitpunkt (in 时候: Zeit)", word:"小时候", wordPy:"xiǎoshíhou", wordDe:"als Kind, in der Kindheit" },
      "以": { py:"yǐ", de:"mit, mittels (in 以茶代酒)", word:"以茶代酒", wordPy:"yǐ chá dài jiǔ", wordDe:"mit Tee statt Wein anstoßen" },
      "代": { py:"dài", de:"ersetzen, anstelle von", word:"以茶代酒", wordPy:"yǐ chá dài jiǔ", wordDe:"mit Tee statt Wein anstoßen" },
      "酒": { py:"jiǔ", de:"Alkohol, Wein", word:"以茶代酒", wordPy:"yǐ chá dài jiǔ", wordDe:"mit Tee statt Wein anstoßen" },
      "我": { py:"wǒ", de:"ich (aus Kapitel 01)", word:"我请客", wordPy:"wǒ qǐngkè", wordDe:"ich lade ein", review:true },
      "请": { py:"qǐng", de:"bitten; einladen (aus 请问)", word:"我请客", wordPy:"wǒ qǐngkè", wordDe:"ich lade ein", review:true },
      "客": { py:"kè", de:"Gast (aus 不客气)", word:"我请客", wordPy:"wǒ qǐngkè", wordDe:"ich lade ein", review:true },
      "够": { py:"gòu", de:"genug", word:"够了", wordPy:"gòu le", wordDe:"das reicht, genug" },
      "了": { py:"le", de:"Partikel (Zustand erreicht) (aus 丢了)", word:"够了", wordPy:"gòu le", wordDe:"das reicht, genug", review:true },
      "过": { py:"guo", de:"Partikel (schon einmal, Erfahrung)", word:"吃过", wordPy:"chīguo", wordDe:"schon einmal gegessen" }
    }
  },
  "08": {
    order: ["爸","妈","哥","弟","姐","妹","老","师","医","生","学","大","今","年","岁","都","工","作","他","们","做","给","忙","程","经","济","设","计","兄","一","个","多","样","带","胡","同"],
    chars: {
      "爸": { py:"bà", de:"Vater", word:"爸爸", wordPy:"bàba", wordDe:"Vater, Papa" },
      "妈": { py:"mā", de:"Mutter", word:"妈妈", wordPy:"māma", wordDe:"Mutter, Mama" },
      "哥": { py:"gē", de:"älterer Bruder", word:"哥哥", wordPy:"gēge", wordDe:"älterer Bruder" },
      "弟": { py:"dì", de:"jüngerer Bruder", word:"弟弟", wordPy:"dìdi", wordDe:"jüngerer Bruder" },
      "姐": { py:"jiě", de:"ältere Schwester", word:"姐姐", wordPy:"jiějie", wordDe:"ältere Schwester" },
      "妹": { py:"mèi", de:"jüngere Schwester", word:"妹妹", wordPy:"mèimei", wordDe:"jüngere Schwester" },
      "老": { py:"lǎo", de:"alt; (Vorsilbe bei Personen)", word:"老师", wordPy:"lǎoshī", wordDe:"Lehrer/in" },
      "师": { py:"shī", de:"Meister, Lehrer (in 老师)", word:"老师", wordPy:"lǎoshī", wordDe:"Lehrer/in" },
      "医": { py:"yī", de:"Medizin, heilen", word:"医生", wordPy:"yīshēng", wordDe:"Arzt, Ärztin" },
      "生": { py:"shēng", de:"geboren werden; (Person) (in 医生: Arzt)", word:"医生", wordPy:"yīshēng", wordDe:"Arzt, Ärztin" },
      "学": { py:"xué", de:"lernen, studieren", word:"学", wordPy:"xué", wordDe:"lernen, studieren" },
      "大": { py:"dà", de:"groß (in 大学: Universität)", word:"大学", wordPy:"dàxué", wordDe:"Universität" },
      "今": { py:"jīn", de:"jetzt, heute (in 今年: dieses Jahr)", word:"今年", wordPy:"jīnnián", wordDe:"dieses Jahr" },
      "年": { py:"nián", de:"Jahr", word:"今年", wordPy:"jīnnián", wordDe:"dieses Jahr" },
      "岁": { py:"suì", de:"Jahre (alt)", word:"岁", wordPy:"suì", wordDe:"Jahre (alt)" },
      "都": { py:"dōu", de:"alle, beide; jeweils", word:"都", wordPy:"dōu", wordDe:"alle, beide; jeweils" },
      "工": { py:"gōng", de:"Arbeit (in 工作)", word:"工作", wordPy:"gōngzuò", wordDe:"arbeiten; Arbeit" },
      "作": { py:"zuò", de:"tun, machen (in 工作)", word:"工作", wordPy:"gōngzuò", wordDe:"arbeiten; Arbeit" },
      "他": { py:"tā", de:"er", word:"他们", wordPy:"tāmen", wordDe:"sie (Plural)" },
      "们": { py:"men", de:"Plural-Silbe (in 我们/他们)", word:"他们", wordPy:"tāmen", wordDe:"sie (Plural)" },
      "做": { py:"zuò", de:"machen, tun", word:"做", wordPy:"zuò", wordDe:"machen, tun" },
      "给": { py:"gěi", de:"geben", word:"给", wordPy:"gěi", wordDe:"geben" },
      "忙": { py:"máng", de:"beschäftigt, viel zu tun", word:"忙", wordPy:"máng", wordDe:"beschäftigt, viel zu tun" },
      "程": { py:"chéng", de:"Verlauf, Strecke (in 工程师: Ingenieur)", word:"工程师", wordPy:"gōngchéngshī", wordDe:"Ingenieur/in" },
      "经": { py:"jīng", de:"durchlaufen; (in 经济: Wirtschaft)", word:"经济", wordPy:"jīngjì", wordDe:"Wirtschaft" },
      "济": { py:"jì", de:"helfen; (in 经济: Wirtschaft)", word:"经济", wordPy:"jīngjì", wordDe:"Wirtschaft" },
      "设": { py:"shè", de:"einrichten, gestalten (in 设计)", word:"设计", wordPy:"shèjì", wordDe:"Design, gestalten" },
      "计": { py:"jì", de:"planen, rechnen (in 设计)", word:"设计", wordPy:"shèjì", wordDe:"Design, gestalten" },
      "兄": { py:"xiōng", de:"älterer Bruder (in 兄弟姐妹)", word:"兄弟姐妹", wordPy:"xiōngdì jiěmèi", wordDe:"Geschwister" },
      "一": { py:"yī", de:"eins (aus 一下)", word:"一个", wordPy:"yí ge", wordDe:"ein, eine", review:true },
      "个": { py:"ge", de:"Stück (Standard-Zählwort) (aus 哪个)", word:"一个", wordPy:"yí ge", wordDe:"ein, eine", review:true },
      "多": { py:"duō", de:"viel (aus 多少)", word:"多大", wordPy:"duō dà", wordDe:"wie alt", review:true },
      "样": { py:"yàng", de:"Art, Aussehen (in 一样: gleich)", word:"一样", wordPy:"yíyàng", wordDe:"gleich, genauso" },
      "带": { py:"dài", de:"mitnehmen, mitbringen", word:"带", wordPy:"dài", wordDe:"mitnehmen, mitbringen" },
      "胡": { py:"hú", de:"(in 胡同: Gasse)", word:"胡同", wordPy:"hútòng", wordDe:"Hutong (traditionelle Gasse)" },
      "同": { py:"tóng", de:"gleich, gemeinsam (in 胡同)", word:"胡同", wordPy:"hútòng", wordDe:"Hutong (traditionelle Gasse)" }
    }
  }};

